### ISSUE TITLE
CreatedMessage instanceof BasicMessageSuccess

### ISSUE THREAD

**Issue by rvillar** [investira/investira.sdk.js#5]
Verificar em que situação CreatedMessage instanceof BasicMessageSuccess = false.
Pelo teste unitário test_messages a condição acima, é true.

**Comment by albertoavila** [comment]
![image](https://user-images.githubusercontent.com/24842839/59708877-0f7a0b80-91dc-11e9-8cfe-98403d954b34.png)
Ao criar a mensagem de resposta o teste funciona (imagem a cima).
No passo seguinte, ao entrar na função pResolve, o teste já não funciona (imagem abaixo, linha 46).
![image](https://user-images.githubusercontent.com/24842839/59709143-78618380-91dc-11e9-9928-4eecfde466be.png)
Até o momento, não consegui identificar onde e/ou porquê o programa está se perdendo.

**Comment by rvillar** [comment]
Re-testar fazendo executando o npm update antes.
